name: Code checks

on:
    push:
        branches: [streamlit_app]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install python
              uses: actions/setup-python@v4
              with:
                python-version: 3.12.3
            - name: Dependencies installation
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                python3 -m pip install pandas-stubs
            - name: Run pylint
              run:  pylint app.py
            - name: Run mypy
              run: mypy .